import type { LibraryMeta } from '../types/dropzone';

export const LIBRARIES: Record<string, LibraryMeta> = {
  reactDropzone: {
    id: 'react-dropzone',
    name: 'react-dropzone',
    description: 'Simple HTML5 drag-and-drop zone with React. Lightweight, hooks-based, zero dependencies.',
    githubUrl: 'https://github.com/react-dropzone/react-dropzone',
    npmUrl: 'https://www.npmjs.com/package/react-dropzone',
    weeklyDownloads: '~7.1M',
    stars: '10.9K',
    license: 'MIT',
    lastRelease: 'v14+',
    gzippedSize: '~3.5 kB',
  },
  uppy: {
    id: 'uppy',
    name: '@uppy/react + @uppy/core',
    description: 'Modular file uploader with plugins for resumable uploads, cloud sources, and more.',
    githubUrl: 'https://github.com/transloadit/uppy',
    npmUrl: 'https://www.npmjs.com/package/@uppy/react',
    weeklyDownloads: '~298K',
    stars: '30.3K',
    license: 'MIT',
    lastRelease: 'v5+',
    gzippedSize: '~25 kB',
  },
  filepond: {
    id: 'filepond',
    name: 'react-filepond + filepond',
    description: 'Feature-rich file upload widget with image preview, encoding, and plugin ecosystem.',
    githubUrl: 'https://github.com/pqina/react-filepond',
    npmUrl: 'https://www.npmjs.com/package/react-filepond',
    weeklyDownloads: '~204K',
    stars: '16.3K',
    license: 'MIT',
    lastRelease: 'Active',
    gzippedSize: '~16 kB',
  },
  reactUploady: {
    id: 'react-uploady',
    name: '@rpldy/uploady',
    description: 'Modern context-based upload framework for React with composable hooks and custom UI.',
    githubUrl: 'https://github.com/rpldy/react-uploady',
    npmUrl: 'https://www.npmjs.com/package/@rpldy/uploady',
    weeklyDownloads: '~34K',
    stars: '1.9K',
    license: 'MIT',
    lastRelease: 'Active',
    gzippedSize: '~6 kB',
  },
};
